package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

/**
 * WhOrderRecipient generated by hbm2java
 */
public class WhOrderRecipient implements java.io.Serializable {

	private String orderId;
	private WhOrderHeader whOrderHeader;
	private String name;
	private Integer receiveType;
	private String receiveNo;
	private String mobilePhone;
	private String phone;
	private String country;
	private String province;
	private String city;
	private String district;
	private String address;
	private String postcode;

	public WhOrderRecipient() {
	}

	public WhOrderRecipient(WhOrderHeader whOrderHeader, String name, String receiveNo, String mobilePhone,
			String phone, String country, String province, String city, String district, String address,
			String postcode) {
		this.whOrderHeader = whOrderHeader;
		this.name = name;
		this.receiveNo = receiveNo;
		this.mobilePhone = mobilePhone;
		this.phone = phone;
		this.country = country;
		this.province = province;
		this.city = city;
		this.district = district;
		this.address = address;
		this.postcode = postcode;
	}

	public WhOrderRecipient(WhOrderHeader whOrderHeader, String name, Integer receiveType, String receiveNo,
			String mobilePhone, String phone, String country, String province, String city, String district,
			String address, String postcode) {
		this.whOrderHeader = whOrderHeader;
		this.name = name;
		this.receiveType = receiveType;
		this.receiveNo = receiveNo;
		this.mobilePhone = mobilePhone;
		this.phone = phone;
		this.country = country;
		this.province = province;
		this.city = city;
		this.district = district;
		this.address = address;
		this.postcode = postcode;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public WhOrderHeader getWhOrderHeader() {
		return this.whOrderHeader;
	}

	public void setWhOrderHeader(WhOrderHeader whOrderHeader) {
		this.whOrderHeader = whOrderHeader;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getReceiveType() {
		return this.receiveType;
	}

	public void setReceiveType(Integer receiveType) {
		this.receiveType = receiveType;
	}

	public String getReceiveNo() {
		return this.receiveNo;
	}

	public void setReceiveNo(String receiveNo) {
		this.receiveNo = receiveNo;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

}
