package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

/**
 * WhOrderItems generated by hbm2java
 */
public class WhOrderItems implements java.io.Serializable {

	private WhOrderItemsId id;
	private WhOrderHeader whOrderHeader;
	private int amount;
	private float price;

	public WhOrderItems() {
	}

	public WhOrderItems(WhOrderItemsId id, WhOrderHeader whOrderHeader, int amount, float price) {
		this.id = id;
		this.whOrderHeader = whOrderHeader;
		this.amount = amount;
		this.price = price;
	}

	public WhOrderItemsId getId() {
		return this.id;
	}

	public void setId(WhOrderItemsId id) {
		this.id = id;
	}

	public WhOrderHeader getWhOrderHeader() {
		return this.whOrderHeader;
	}

	public void setWhOrderHeader(WhOrderHeader whOrderHeader) {
		this.whOrderHeader = whOrderHeader;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

}
