package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

/**
 * WhOrderLogisticsFlow generated by hbm2java
 */
public class WhOrderLogisticsFlow implements java.io.Serializable {

	private WhOrderLogisticsFlowId id;
	private WhOrderLogistics whOrderLogistics;
	private String acceptAddress;
	private String acceptStatus;
	private String acceptNotes;

	public WhOrderLogisticsFlow() {
	}

	public WhOrderLogisticsFlow(WhOrderLogisticsFlowId id, WhOrderLogistics whOrderLogistics, String acceptAddress) {
		this.id = id;
		this.whOrderLogistics = whOrderLogistics;
		this.acceptAddress = acceptAddress;
	}

	public WhOrderLogisticsFlow(WhOrderLogisticsFlowId id, WhOrderLogistics whOrderLogistics, String acceptAddress,
			String acceptStatus, String acceptNotes) {
		this.id = id;
		this.whOrderLogistics = whOrderLogistics;
		this.acceptAddress = acceptAddress;
		this.acceptStatus = acceptStatus;
		this.acceptNotes = acceptNotes;
	}

	public WhOrderLogisticsFlowId getId() {
		return this.id;
	}

	public void setId(WhOrderLogisticsFlowId id) {
		this.id = id;
	}

	public WhOrderLogistics getWhOrderLogistics() {
		return this.whOrderLogistics;
	}

	public void setWhOrderLogistics(WhOrderLogistics whOrderLogistics) {
		this.whOrderLogistics = whOrderLogistics;
	}

	public String getAcceptAddress() {
		return this.acceptAddress;
	}

	public void setAcceptAddress(String acceptAddress) {
		this.acceptAddress = acceptAddress;
	}

	public String getAcceptStatus() {
		return this.acceptStatus;
	}

	public void setAcceptStatus(String acceptStatus) {
		this.acceptStatus = acceptStatus;
	}

	public String getAcceptNotes() {
		return this.acceptNotes;
	}

	public void setAcceptNotes(String acceptNotes) {
		this.acceptNotes = acceptNotes;
	}

}
