package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * WhOrderHeader generated by hbm2java
 */
public class WhOrderHeader implements java.io.Serializable {

	private String orderId;
	private WhRefTpl whRefTpl;
	private String orderDate;
	private String customerId;
	private String packingMaterial;
	private String warehouseId;
	private int orderType;
	private String electriccode;
	private String deliveryCode;
	private String notes;
	private String cbepcomcode;
	private Set<WhOrderItems> whOrderItemses = new HashSet<WhOrderItems>(0);
	private WhOrderRecipient whOrderRecipient;
	private WhOrderConfirm whOrderConfirm;

	public WhOrderHeader() {
	}

	public WhOrderHeader(String orderId, WhRefTpl whRefTpl, String orderDate, String customerId, String packingMaterial,
			String warehouseId, int orderType, String electriccode, String deliveryCode, String notes,
			String cbepcomcode) {
		this.orderId = orderId;
		this.whRefTpl = whRefTpl;
		this.orderDate = orderDate;
		this.customerId = customerId;
		this.packingMaterial = packingMaterial;
		this.warehouseId = warehouseId;
		this.orderType = orderType;
		this.electriccode = electriccode;
		this.deliveryCode = deliveryCode;
		this.notes = notes;
		this.cbepcomcode = cbepcomcode;
	}

	public WhOrderHeader(String orderId, WhRefTpl whRefTpl, String orderDate, String customerId, String packingMaterial,
			String warehouseId, int orderType, String electriccode, String deliveryCode, String notes,
			String cbepcomcode, Set<WhOrderItems> whOrderItemses, WhOrderRecipient whOrderRecipient,
			WhOrderConfirm whOrderConfirm) {
		this.orderId = orderId;
		this.whRefTpl = whRefTpl;
		this.orderDate = orderDate;
		this.customerId = customerId;
		this.packingMaterial = packingMaterial;
		this.warehouseId = warehouseId;
		this.orderType = orderType;
		this.electriccode = electriccode;
		this.deliveryCode = deliveryCode;
		this.notes = notes;
		this.cbepcomcode = cbepcomcode;
		this.whOrderItemses = whOrderItemses;
		this.whOrderRecipient = whOrderRecipient;
		this.whOrderConfirm = whOrderConfirm;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public WhRefTpl getWhRefTpl() {
		return this.whRefTpl;
	}

	public void setWhRefTpl(WhRefTpl whRefTpl) {
		this.whRefTpl = whRefTpl;
	}

	public String getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getPackingMaterial() {
		return this.packingMaterial;
	}

	public void setPackingMaterial(String packingMaterial) {
		this.packingMaterial = packingMaterial;
	}

	public String getWarehouseId() {
		return this.warehouseId;
	}

	public void setWarehouseId(String warehouseId) {
		this.warehouseId = warehouseId;
	}

	public int getOrderType() {
		return this.orderType;
	}

	public void setOrderType(int orderType) {
		this.orderType = orderType;
	}

	public String getElectriccode() {
		return this.electriccode;
	}

	public void setElectriccode(String electriccode) {
		this.electriccode = electriccode;
	}

	public String getDeliveryCode() {
		return this.deliveryCode;
	}

	public void setDeliveryCode(String deliveryCode) {
		this.deliveryCode = deliveryCode;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getCbepcomcode() {
		return this.cbepcomcode;
	}

	public void setCbepcomcode(String cbepcomcode) {
		this.cbepcomcode = cbepcomcode;
	}

	public Set<WhOrderItems> getWhOrderItemses() {
		return this.whOrderItemses;
	}

	public void setWhOrderItemses(Set<WhOrderItems> whOrderItemses) {
		this.whOrderItemses = whOrderItemses;
	}

	public WhOrderRecipient getWhOrderRecipient() {
		return this.whOrderRecipient;
	}

	public void setWhOrderRecipient(WhOrderRecipient whOrderRecipient) {
		this.whOrderRecipient = whOrderRecipient;
	}

	public WhOrderConfirm getWhOrderConfirm() {
		return this.whOrderConfirm;
	}

	public void setWhOrderConfirm(WhOrderConfirm whOrderConfirm) {
		this.whOrderConfirm = whOrderConfirm;
	}

}
