package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * WhRefTpl generated by hbm2java
 */
public class WhRefTpl implements java.io.Serializable {

	private String tpl;
	private String tplName;
	private Set<WhOrderHeader> whOrderHeaders = new HashSet<WhOrderHeader>(0);

	public WhRefTpl() {
	}

	public WhRefTpl(String tpl, String tplName) {
		this.tpl = tpl;
		this.tplName = tplName;
	}

	public WhRefTpl(String tpl, String tplName, Set<WhOrderHeader> whOrderHeaders) {
		this.tpl = tpl;
		this.tplName = tplName;
		this.whOrderHeaders = whOrderHeaders;
	}

	public String getTpl() {
		return this.tpl;
	}

	public void setTpl(String tpl) {
		this.tpl = tpl;
	}

	public String getTplName() {
		return this.tplName;
	}

	public void setTplName(String tplName) {
		this.tplName = tplName;
	}

	public Set<WhOrderHeader> getWhOrderHeaders() {
		return this.whOrderHeaders;
	}

	public void setWhOrderHeaders(Set<WhOrderHeader> whOrderHeaders) {
		this.whOrderHeaders = whOrderHeaders;
	}

}
