package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ShopncOrder generated by hbm2java
 */
public class ShopncOrder implements java.io.Serializable {

	private int orderId;
	private String orderSn;
	private int sellerId;
	private int storeId;
	private String storeName;
	private int buyerId;
	private String buyerName;
	private String buyerEmail;
	private String addTime;
	private boolean orderType;
	private int paymentId;
	private String paymentName;
	private String paymentCode;
	private Character paymentDirect;
	private String outSn;
	private String paymentTime;
	private String payMessage;
	private String shippingTime;
	private String shippingCode;
	private String outPaymentCode;
	private String finnshedTime;
	private String invoice;
	private BigDecimal goodsAmount;
	private BigDecimal discount;
	private BigDecimal orderAmount;
	private BigDecimal shippingFee;
	private Boolean evaluationStatus;
	private String evaluationTime;
	private boolean evalsellerStatus;
	private Integer evalsellerTime;
	private String orderMessage;
	private int orderState;
	private int orderPointscount;
	private Integer voucherId;
	private Integer voucherPrice;
	private String voucherCode;
	private Boolean refundState;
	private Boolean returnState;
	private BigDecimal refundAmount;
	private Integer returnNum;
	private Integer groupId;
	private int groupCount;
	private int xianshiId;
	private String xianshiExplain;
	private int mansongId;
	private String mansongExplain;
	private String orderFrom;
	private ShopncOrderAddress shopncOrderAddress;
	private Set<ShopncOrderGoods> shopncOrderGoodses = new HashSet<ShopncOrderGoods>(0);

	public ShopncOrder() {
	}

	public ShopncOrder(int orderId, String orderSn, int sellerId, int storeId, String storeName, int buyerId,
			String buyerName, String buyerEmail, String addTime, boolean orderType, int paymentId, String paymentName,
			String paymentCode, String outSn, BigDecimal goodsAmount, BigDecimal orderAmount, boolean evalsellerStatus,
			int orderState, int orderPointscount, int groupCount, int xianshiId, String xianshiExplain, int mansongId,
			String mansongExplain) {
		this.orderId = orderId;
		this.orderSn = orderSn;
		this.sellerId = sellerId;
		this.storeId = storeId;
		this.storeName = storeName;
		this.buyerId = buyerId;
		this.buyerName = buyerName;
		this.buyerEmail = buyerEmail;
		this.addTime = addTime;
		this.orderType = orderType;
		this.paymentId = paymentId;
		this.paymentName = paymentName;
		this.paymentCode = paymentCode;
		this.outSn = outSn;
		this.goodsAmount = goodsAmount;
		this.orderAmount = orderAmount;
		this.evalsellerStatus = evalsellerStatus;
		this.orderState = orderState;
		this.orderPointscount = orderPointscount;
		this.groupCount = groupCount;
		this.xianshiId = xianshiId;
		this.xianshiExplain = xianshiExplain;
		this.mansongId = mansongId;
		this.mansongExplain = mansongExplain;
	}

	public ShopncOrder(int orderId, String orderSn, int sellerId, int storeId, String storeName, int buyerId,
			String buyerName, String buyerEmail, String addTime, boolean orderType, int paymentId, String paymentName,
			String paymentCode, Character paymentDirect, String outSn, String paymentTime, String payMessage,
			String shippingTime, String shippingCode, String outPaymentCode, String finnshedTime, String invoice,
			BigDecimal goodsAmount, BigDecimal discount, BigDecimal orderAmount, BigDecimal shippingFee,
			Boolean evaluationStatus, String evaluationTime, boolean evalsellerStatus, Integer evalsellerTime,
			String orderMessage, int orderState, int orderPointscount, Integer voucherId, Integer voucherPrice,
			String voucherCode, Boolean refundState, Boolean returnState, BigDecimal refundAmount, Integer returnNum,
			Integer groupId, int groupCount, int xianshiId, String xianshiExplain, int mansongId, String mansongExplain,
			String orderFrom, ShopncOrderAddress shopncOrderAddress, Set<ShopncOrderGoods> shopncOrderGoodses) {
		this.orderId = orderId;
		this.orderSn = orderSn;
		this.sellerId = sellerId;
		this.storeId = storeId;
		this.storeName = storeName;
		this.buyerId = buyerId;
		this.buyerName = buyerName;
		this.buyerEmail = buyerEmail;
		this.addTime = addTime;
		this.orderType = orderType;
		this.paymentId = paymentId;
		this.paymentName = paymentName;
		this.paymentCode = paymentCode;
		this.paymentDirect = paymentDirect;
		this.outSn = outSn;
		this.paymentTime = paymentTime;
		this.payMessage = payMessage;
		this.shippingTime = shippingTime;
		this.shippingCode = shippingCode;
		this.outPaymentCode = outPaymentCode;
		this.finnshedTime = finnshedTime;
		this.invoice = invoice;
		this.goodsAmount = goodsAmount;
		this.discount = discount;
		this.orderAmount = orderAmount;
		this.shippingFee = shippingFee;
		this.evaluationStatus = evaluationStatus;
		this.evaluationTime = evaluationTime;
		this.evalsellerStatus = evalsellerStatus;
		this.evalsellerTime = evalsellerTime;
		this.orderMessage = orderMessage;
		this.orderState = orderState;
		this.orderPointscount = orderPointscount;
		this.voucherId = voucherId;
		this.voucherPrice = voucherPrice;
		this.voucherCode = voucherCode;
		this.refundState = refundState;
		this.returnState = returnState;
		this.refundAmount = refundAmount;
		this.returnNum = returnNum;
		this.groupId = groupId;
		this.groupCount = groupCount;
		this.xianshiId = xianshiId;
		this.xianshiExplain = xianshiExplain;
		this.mansongId = mansongId;
		this.mansongExplain = mansongExplain;
		this.orderFrom = orderFrom;
		this.shopncOrderAddress = shopncOrderAddress;
		this.shopncOrderGoodses = shopncOrderGoodses;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public String getOrderSn() {
		return this.orderSn;
	}

	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn;
	}

	public int getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public int getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(int buyerId) {
		this.buyerId = buyerId;
	}

	public String getBuyerName() {
		return this.buyerName;
	}

	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	public String getBuyerEmail() {
		return this.buyerEmail;
	}

	public void setBuyerEmail(String buyerEmail) {
		this.buyerEmail = buyerEmail;
	}

	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	public boolean isOrderType() {
		return this.orderType;
	}

	public void setOrderType(boolean orderType) {
		this.orderType = orderType;
	}

	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public String getPaymentName() {
		return this.paymentName;
	}

	public void setPaymentName(String paymentName) {
		this.paymentName = paymentName;
	}

	public String getPaymentCode() {
		return this.paymentCode;
	}

	public void setPaymentCode(String paymentCode) {
		this.paymentCode = paymentCode;
	}

	public Character getPaymentDirect() {
		return this.paymentDirect;
	}

	public void setPaymentDirect(Character paymentDirect) {
		this.paymentDirect = paymentDirect;
	}

	public String getOutSn() {
		return this.outSn;
	}

	public void setOutSn(String outSn) {
		this.outSn = outSn;
	}

	public String getPaymentTime() {
		return this.paymentTime;
	}

	public void setPaymentTime(String paymentTime) {
		this.paymentTime = paymentTime;
	}

	public String getPayMessage() {
		return this.payMessage;
	}

	public void setPayMessage(String payMessage) {
		this.payMessage = payMessage;
	}

	public String getShippingTime() {
		return this.shippingTime;
	}

	public void setShippingTime(String shippingTime) {
		this.shippingTime = shippingTime;
	}

	public String getShippingCode() {
		return this.shippingCode;
	}

	public void setShippingCode(String shippingCode) {
		this.shippingCode = shippingCode;
	}

	public String getOutPaymentCode() {
		return this.outPaymentCode;
	}

	public void setOutPaymentCode(String outPaymentCode) {
		this.outPaymentCode = outPaymentCode;
	}

	public String getFinnshedTime() {
		return this.finnshedTime;
	}

	public void setFinnshedTime(String finnshedTime) {
		this.finnshedTime = finnshedTime;
	}

	public String getInvoice() {
		return this.invoice;
	}

	public void setInvoice(String invoice) {
		this.invoice = invoice;
	}

	public BigDecimal getGoodsAmount() {
		return this.goodsAmount;
	}

	public void setGoodsAmount(BigDecimal goodsAmount) {
		this.goodsAmount = goodsAmount;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	public BigDecimal getShippingFee() {
		return this.shippingFee;
	}

	public void setShippingFee(BigDecimal shippingFee) {
		this.shippingFee = shippingFee;
	}

	public Boolean getEvaluationStatus() {
		return this.evaluationStatus;
	}

	public void setEvaluationStatus(Boolean evaluationStatus) {
		this.evaluationStatus = evaluationStatus;
	}

	public String getEvaluationTime() {
		return this.evaluationTime;
	}

	public void setEvaluationTime(String evaluationTime) {
		this.evaluationTime = evaluationTime;
	}

	public boolean isEvalsellerStatus() {
		return this.evalsellerStatus;
	}

	public void setEvalsellerStatus(boolean evalsellerStatus) {
		this.evalsellerStatus = evalsellerStatus;
	}

	public Integer getEvalsellerTime() {
		return this.evalsellerTime;
	}

	public void setEvalsellerTime(Integer evalsellerTime) {
		this.evalsellerTime = evalsellerTime;
	}

	public String getOrderMessage() {
		return this.orderMessage;
	}

	public void setOrderMessage(String orderMessage) {
		this.orderMessage = orderMessage;
	}

	public int getOrderState() {
		return this.orderState;
	}

	public void setOrderState(int orderState) {
		this.orderState = orderState;
	}

	public int getOrderPointscount() {
		return this.orderPointscount;
	}

	public void setOrderPointscount(int orderPointscount) {
		this.orderPointscount = orderPointscount;
	}

	public Integer getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(Integer voucherId) {
		this.voucherId = voucherId;
	}

	public Integer getVoucherPrice() {
		return this.voucherPrice;
	}

	public void setVoucherPrice(Integer voucherPrice) {
		this.voucherPrice = voucherPrice;
	}

	public String getVoucherCode() {
		return this.voucherCode;
	}

	public void setVoucherCode(String voucherCode) {
		this.voucherCode = voucherCode;
	}

	public Boolean getRefundState() {
		return this.refundState;
	}

	public void setRefundState(Boolean refundState) {
		this.refundState = refundState;
	}

	public Boolean getReturnState() {
		return this.returnState;
	}

	public void setReturnState(Boolean returnState) {
		this.returnState = returnState;
	}

	public BigDecimal getRefundAmount() {
		return this.refundAmount;
	}

	public void setRefundAmount(BigDecimal refundAmount) {
		this.refundAmount = refundAmount;
	}

	public Integer getReturnNum() {
		return this.returnNum;
	}

	public void setReturnNum(Integer returnNum) {
		this.returnNum = returnNum;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public int getGroupCount() {
		return this.groupCount;
	}

	public void setGroupCount(int groupCount) {
		this.groupCount = groupCount;
	}

	public int getXianshiId() {
		return this.xianshiId;
	}

	public void setXianshiId(int xianshiId) {
		this.xianshiId = xianshiId;
	}

	public String getXianshiExplain() {
		return this.xianshiExplain;
	}

	public void setXianshiExplain(String xianshiExplain) {
		this.xianshiExplain = xianshiExplain;
	}

	public int getMansongId() {
		return this.mansongId;
	}

	public void setMansongId(int mansongId) {
		this.mansongId = mansongId;
	}

	public String getMansongExplain() {
		return this.mansongExplain;
	}

	public void setMansongExplain(String mansongExplain) {
		this.mansongExplain = mansongExplain;
	}

	public String getOrderFrom() {
		return this.orderFrom;
	}

	public void setOrderFrom(String orderFrom) {
		this.orderFrom = orderFrom;
	}

	public ShopncOrderAddress getShopncOrderAddress() {
		return this.shopncOrderAddress;
	}

	public void setShopncOrderAddress(ShopncOrderAddress shopncOrderAddress) {
		this.shopncOrderAddress = shopncOrderAddress;
	}

	public Set<ShopncOrderGoods> getShopncOrderGoodses() {
		return this.shopncOrderGoodses;
	}

	public void setShopncOrderGoodses(Set<ShopncOrderGoods> shopncOrderGoodses) {
		this.shopncOrderGoodses = shopncOrderGoodses;
	}

}
