package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

/**
 * ShopncOrderGoodsId generated by hbm2java
 */
public class ShopncOrderGoodsId implements java.io.Serializable {

	private int orderId;
	private int goodsId;

	public ShopncOrderGoodsId() {
	}

	public ShopncOrderGoodsId(int orderId, int goodsId) {
		this.orderId = orderId;
		this.goodsId = goodsId;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(int goodsId) {
		this.goodsId = goodsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopncOrderGoodsId))
			return false;
		ShopncOrderGoodsId castOther = (ShopncOrderGoodsId) other;

		return (this.getOrderId() == castOther.getOrderId()) && (this.getGoodsId() == castOther.getGoodsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getGoodsId();
		return result;
	}

}
