package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

/**
 * ShopncOrderAddress generated by hbm2java
 */
public class ShopncOrderAddress implements java.io.Serializable {

	private int orderId;
	private ShopncOrder shopncOrder;
	private String trueName;
	private int areaId;
	private String areaInfo;
	private String address;
	private String zipCode;
	private String telPhone;
	private String mobPhone;

	public ShopncOrderAddress() {
	}

	public ShopncOrderAddress(ShopncOrder shopncOrder, String trueName, int areaId, String areaInfo, String address,
			String zipCode, String telPhone, String mobPhone) {
		this.shopncOrder = shopncOrder;
		this.trueName = trueName;
		this.areaId = areaId;
		this.areaInfo = areaInfo;
		this.address = address;
		this.zipCode = zipCode;
		this.telPhone = telPhone;
		this.mobPhone = mobPhone;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public ShopncOrder getShopncOrder() {
		return this.shopncOrder;
	}

	public void setShopncOrder(ShopncOrder shopncOrder) {
		this.shopncOrder = shopncOrder;
	}

	public String getTrueName() {
		return this.trueName;
	}

	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}

	public int getAreaId() {
		return this.areaId;
	}

	public void setAreaId(int areaId) {
		this.areaId = areaId;
	}

	public String getAreaInfo() {
		return this.areaInfo;
	}

	public void setAreaInfo(String areaInfo) {
		this.areaInfo = areaInfo;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getTelPhone() {
		return this.telPhone;
	}

	public void setTelPhone(String telPhone) {
		this.telPhone = telPhone;
	}

	public String getMobPhone() {
		return this.mobPhone;
	}

	public void setMobPhone(String mobPhone) {
		this.mobPhone = mobPhone;
	}

}
