package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ShopncOrderGoods generated by hbm2java
 */
public class ShopncOrderGoods implements java.io.Serializable {

	private ShopncOrderGoodsId id;
	private ShopncOrder shopncOrder;
	private int recId;
	private String goodsName;
	private int specId;
	private String specInfo;
	private BigDecimal goodsPrice;
	private int goodsNum;
	private String goodsImage;
	private Integer goodsReturnnum;
	private BigDecimal shippingFee;
	private String shippingName;

	public ShopncOrderGoods() {
	}

	public ShopncOrderGoods(ShopncOrderGoodsId id, ShopncOrder shopncOrder, int recId, String goodsName, int specId,
			BigDecimal goodsPrice, int goodsNum) {
		this.id = id;
		this.shopncOrder = shopncOrder;
		this.recId = recId;
		this.goodsName = goodsName;
		this.specId = specId;
		this.goodsPrice = goodsPrice;
		this.goodsNum = goodsNum;
	}

	public ShopncOrderGoods(ShopncOrderGoodsId id, ShopncOrder shopncOrder, int recId, String goodsName, int specId,
			String specInfo, BigDecimal goodsPrice, int goodsNum, String goodsImage, Integer goodsReturnnum,
			BigDecimal shippingFee, String shippingName) {
		this.id = id;
		this.shopncOrder = shopncOrder;
		this.recId = recId;
		this.goodsName = goodsName;
		this.specId = specId;
		this.specInfo = specInfo;
		this.goodsPrice = goodsPrice;
		this.goodsNum = goodsNum;
		this.goodsImage = goodsImage;
		this.goodsReturnnum = goodsReturnnum;
		this.shippingFee = shippingFee;
		this.shippingName = shippingName;
	}

	public ShopncOrderGoodsId getId() {
		return this.id;
	}

	public void setId(ShopncOrderGoodsId id) {
		this.id = id;
	}

	public ShopncOrder getShopncOrder() {
		return this.shopncOrder;
	}

	public void setShopncOrder(ShopncOrder shopncOrder) {
		this.shopncOrder = shopncOrder;
	}

	public int getRecId() {
		return this.recId;
	}

	public void setRecId(int recId) {
		this.recId = recId;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public int getSpecId() {
		return this.specId;
	}

	public void setSpecId(int specId) {
		this.specId = specId;
	}

	public String getSpecInfo() {
		return this.specInfo;
	}

	public void setSpecInfo(String specInfo) {
		this.specInfo = specInfo;
	}

	public BigDecimal getGoodsPrice() {
		return this.goodsPrice;
	}

	public void setGoodsPrice(BigDecimal goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	public int getGoodsNum() {
		return this.goodsNum;
	}

	public void setGoodsNum(int goodsNum) {
		this.goodsNum = goodsNum;
	}

	public String getGoodsImage() {
		return this.goodsImage;
	}

	public void setGoodsImage(String goodsImage) {
		this.goodsImage = goodsImage;
	}

	public Integer getGoodsReturnnum() {
		return this.goodsReturnnum;
	}

	public void setGoodsReturnnum(Integer goodsReturnnum) {
		this.goodsReturnnum = goodsReturnnum;
	}

	public BigDecimal getShippingFee() {
		return this.shippingFee;
	}

	public void setShippingFee(BigDecimal shippingFee) {
		this.shippingFee = shippingFee;
	}

	public String getShippingName() {
		return this.shippingName;
	}

	public void setShippingName(String shippingName) {
		this.shippingName = shippingName;
	}

}
