package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * WhGoodsEntry generated by hbm2java
 */
public class WhGoodsEntry implements java.io.Serializable {

	private String orderNo;
	private String reportId;
	private Date applyTime;
	private int status;
	private String notes;

	public WhGoodsEntry() {
	}

	public WhGoodsEntry(String orderNo, String reportId, Date applyTime, int status) {
		this.orderNo = orderNo;
		this.reportId = reportId;
		this.applyTime = applyTime;
		this.status = status;
	}

	public WhGoodsEntry(String orderNo, String reportId, Date applyTime, int status, String notes) {
		this.orderNo = orderNo;
		this.reportId = reportId;
		this.applyTime = applyTime;
		this.status = status;
		this.notes = notes;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
