package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

/**
 * WhOrderConfirm generated by hbm2java
 */
public class WhOrderConfirm implements java.io.Serializable {

	private String orderId;
	private WhOrderHeader whOrderHeader;
	private int status;
	private String notes;

	public WhOrderConfirm() {
	}

	public WhOrderConfirm(WhOrderHeader whOrderHeader, int status) {
		this.whOrderHeader = whOrderHeader;
		this.status = status;
	}

	public WhOrderConfirm(WhOrderHeader whOrderHeader, int status, String notes) {
		this.whOrderHeader = whOrderHeader;
		this.status = status;
		this.notes = notes;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public WhOrderHeader getWhOrderHeader() {
		return this.whOrderHeader;
	}

	public void setWhOrderHeader(WhOrderHeader whOrderHeader) {
		this.whOrderHeader = whOrderHeader;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
