package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

/**
 * WhOrderDelivery generated by hbm2java
 */
public class WhOrderDelivery implements java.io.Serializable {

	private String enOrderCode;
	private String wayBillNo;
	private String logisticsName;
	private String notes;
	private String logisticsId;

	public WhOrderDelivery() {
	}

	public WhOrderDelivery(String enOrderCode, String wayBillNo, String logisticsName) {
		this.enOrderCode = enOrderCode;
		this.wayBillNo = wayBillNo;
		this.logisticsName = logisticsName;
	}

	public WhOrderDelivery(String enOrderCode, String wayBillNo, String logisticsName, String notes,
			String logisticsId) {
		this.enOrderCode = enOrderCode;
		this.wayBillNo = wayBillNo;
		this.logisticsName = logisticsName;
		this.notes = notes;
		this.logisticsId = logisticsId;
	}

	public String getEnOrderCode() {
		return this.enOrderCode;
	}

	public void setEnOrderCode(String enOrderCode) {
		this.enOrderCode = enOrderCode;
	}

	public String getWayBillNo() {
		return this.wayBillNo;
	}

	public void setWayBillNo(String wayBillNo) {
		this.wayBillNo = wayBillNo;
	}

	public String getLogisticsName() {
		return this.logisticsName;
	}

	public void setLogisticsName(String logisticsName) {
		this.logisticsName = logisticsName;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getLogisticsId() {
		return this.logisticsId;
	}

	public void setLogisticsId(String logisticsId) {
		this.logisticsId = logisticsId;
	}

}
