package CigouDAO.cigoudb;
// Generated 2016-4-16 23:41:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * WhOrderLogisticsFlowId generated by hbm2java
 */
public class WhOrderLogisticsFlowId implements java.io.Serializable {

	private String orderId;
	private Date acceptTime;

	public WhOrderLogisticsFlowId() {
	}

	public WhOrderLogisticsFlowId(String orderId, Date acceptTime) {
		this.orderId = orderId;
		this.acceptTime = acceptTime;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public Date getAcceptTime() {
		return this.acceptTime;
	}

	public void setAcceptTime(Date acceptTime) {
		this.acceptTime = acceptTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WhOrderLogisticsFlowId))
			return false;
		WhOrderLogisticsFlowId castOther = (WhOrderLogisticsFlowId) other;

		return ((this.getOrderId() == castOther.getOrderId()) || (this.getOrderId() != null
				&& castOther.getOrderId() != null && this.getOrderId().equals(castOther.getOrderId())))
				&& ((this.getAcceptTime() == castOther.getAcceptTime())
						|| (this.getAcceptTime() != null && castOther.getAcceptTime() != null
								&& this.getAcceptTime().equals(castOther.getAcceptTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37 * result + (getAcceptTime() == null ? 0 : this.getAcceptTime().hashCode());
		return result;
	}

}
